import { useEffect, useState } from 'react';
import { formatFen, type HistoryMonth, type Ledger } from '@auto-reimbursement/contracts';
import { api, apiUrl, openAuthed } from '../api';
import { apiFor } from '../ledgerApi';
import { sayFor } from '../wording';

export function HistoryPage({ onPreview, ledger = 'store' }: { onPreview: (id: string) => void; ledger?: Ledger }): React.JSX.Element {
  // 历史、归档、清理都只管这个区的批次；店内 client 就是 api 本身
  const client = apiFor(ledger);
  const say = sayFor(ledger);
  const [months, setMonths] = useState<HistoryMonth[]>([]); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [cleanupMonth, setCleanupMonth] = useState<string | null>(null); const [confirmation, setConfirmation] = useState('');
  const refresh = () => void client.history().then(setMonths, (reason: unknown) => setError(reason instanceof Error ? reason.message : '加载历史失败'));
  useEffect(refresh, []);
  async function archive(month: string, active: boolean): Promise<void> { try { await (active ? client.unarchive(month) : client.archive(month)); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '归档失败'); } }
  async function cleanup(): Promise<void> { if (!cleanupMonth) return; try { await client.cleanup(cleanupMonth, confirmation); setCleanupMonth(null); setConfirmation(''); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '清理失败'); } }
  async function cancel(id: string): Promise<void> { if (!window.confirm(say('撤销后票据将退回本次报销池，已生成的 PDF 仅保留为作废件。确定撤销本单报销吗？'))) return; try { await client.cancelBatch(id); setMessage(say('已撤销，票据已退回本次报销池。')); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : say('撤销报销失败')); } }
  return <main className="page-content"><h2>{say('历史报销单')}</h2>{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}{months.length === 0 && <p>{say('暂无历史报销单。')}</p>}{months.map(({ month, batches }) => { const active = batches.filter((batch) => !batch.cancelledAt); const archived = active.length > 0 && active.every((batch) => batch.archivedAt !== null); /* P-31：归档状态只按未撤销的批次判断，archiveMonth 会跳过已撤销批次；正常批次没有 cancelledAt 字段，不能用 === null 判断 */ return <section className="history-month" key={month}><h3>{month}</h3><button type="button" onClick={() => void archive(month, archived)}>{archived ? '取消归档' : '归档本月'}</button><button type="button" onClick={() => setCleanupMonth(month)}>清理原始图片</button>{batches.map((batch) => <article key={batch.id}><p>合计：{formatFen(batch.totalFen)} {batch.archivedAt ? '（已归档）' : ''}{batch.cancelledAt ? '（已撤销）' : ''}</p><p>{batch.pdfPath ? (batch.cancelledAt ? <a href={apiUrl(`/api/batches/${batch.id}/pdf`)} onClick={(event) => { event.preventDefault(); void openAuthed(`/api/batches/${batch.id}/pdf`); }}>作废 PDF（仅留存备查）</a> : <a href={apiUrl(`/api/batches/${batch.id}/pdf`)} onClick={(event) => { event.preventDefault(); void openAuthed(`/api/batches/${batch.id}/pdf`); }}>已保存 PDF</a>) : '尚未生成 PDF'}</p><p>{say('原始凭证')} {batch.items.map((item) => <a key={item.receiptId} href={api.imageUrl(item.original.id)} onClick={(event) => { event.preventDefault(); void openAuthed(`/api/images/${encodeURIComponent(item.original.id)}`); }}>原件</a>)}{ledger === 'store' && <>；退款凭证 {batch.items.flatMap((item) => item.refundImages).map((image) => <a key={image.id} href={api.imageUrl(image.id)} onClick={(event) => { event.preventDefault(); void openAuthed(`/api/images/${encodeURIComponent(image.id)}`); }}>退款凭证</a>)}</>}</p>{batch.cancelledAt ? null : <button type="button" onClick={() => onPreview(batch.id)}>对账 / 查看</button>}{batch.cancelledAt ? null : <button type="button" onClick={() => void cancel(batch.id)}>{say('撤销本单报销')}</button>}</article>)}</section>; })}{cleanupMonth && <section role="dialog" aria-label="确认清理原始图片"><h3>确认清理 {cleanupMonth}</h3><p>{ledger === 'store' ? '此操作仅删除已归档报销单的原始付款图片，不会删除退款凭证或 PDF。' : '此操作仅删除已归档付款单的原始回单图片，不会删除 PDF。'}</p><label>请输入 DELETE ORIGINALS {cleanupMonth}<input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /></label><button type="button" disabled={confirmation !== `DELETE ORIGINALS ${cleanupMonth}`} onClick={() => void cleanup()}>确认清理</button><button type="button" onClick={() => setCleanupMonth(null)}>取消</button></section>}</main>;
}
