import { useEffect, useState } from 'react';
import { formatFen, type HistoryMonth } from '@auto-reimbursement/contracts';
import { api, apiUrl } from '../api';

export function HistoryPage({ onPreview }: { onPreview: (id: string) => void }): React.JSX.Element {
  const [months, setMonths] = useState<HistoryMonth[]>([]); const [error, setError] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null); const [cleanupMonth, setCleanupMonth] = useState<string | null>(null); const [confirmation, setConfirmation] = useState('');
  const refresh = () => void api.history().then(setMonths, (reason: unknown) => setError(reason instanceof Error ? reason.message : '加载历史失败'));
  useEffect(refresh, []);
  async function archive(month: string, active: boolean): Promise<void> { try { await (active ? api.unarchive(month) : api.archive(month)); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '归档失败'); } }
  async function cleanup(): Promise<void> { if (!cleanupMonth) return; try { await api.cleanup(cleanupMonth, confirmation); setCleanupMonth(null); setConfirmation(''); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '清理失败'); } }
  async function cancel(id: string): Promise<void> { if (!window.confirm('撤销后票据将退回本次报销池，已生成的 PDF 仅保留为作废件。确定撤销本单报销吗？')) return; try { await api.cancelBatch(id); setMessage('已撤销，票据已退回本次报销池。'); refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : '撤销报销失败'); } }
  return <main className="page-content"><h2>历史报销单</h2>{error && <p role="alert">{error}</p>}{message && <p role="status">{message}</p>}{months.length === 0 && <p>暂无历史报销单。</p>}{months.map(({ month, batches }) => { const archived = batches.length > 0 && batches.every((batch) => batch.archivedAt !== null); return <section className="history-month" key={month}><h3>{month}</h3><button type="button" onClick={() => void archive(month, archived)}>{archived ? '取消归档' : '归档本月'}</button><button type="button" onClick={() => setCleanupMonth(month)}>清理原始图片</button>{batches.map((batch) => <article key={batch.id}><p>合计：{formatFen(batch.totalFen)} {batch.archivedAt ? '（已归档）' : ''}{batch.cancelledAt ? '（已撤销）' : ''}</p><p>{batch.pdfPath ? (batch.cancelledAt ? <a href={apiUrl(`/api/batches/${batch.id}/pdf`)}>作废 PDF（仅留存备查）</a> : <a href={apiUrl(`/api/batches/${batch.id}/pdf`)}>已保存 PDF</a>) : '尚未生成 PDF'}</p><p>原始凭证 {batch.items.map((item) => <a key={item.receiptId} href={api.imageUrl(item.original.id)}>原件</a>)}；退款凭证 {batch.items.flatMap((item) => item.refundImages).map((image) => <a key={image.id} href={api.imageUrl(image.id)}>退款凭证</a>)}</p>{batch.cancelledAt ? null : <button type="button" onClick={() => onPreview(batch.id)}>查看预览</button>}{batch.cancelledAt ? null : <button type="button" onClick={() => void cancel(batch.id)}>撤销本单报销</button>}</article>)}</section>; })}{cleanupMonth && <section role="dialog" aria-label="确认清理原始图片"><h3>确认清理 {cleanupMonth}</h3><p>此操作仅删除已归档报销单的原始付款图片，不会删除退款凭证或 PDF。</p><label>请输入 DELETE ORIGINALS {cleanupMonth}<input value={confirmation} onChange={(e) => setConfirmation(e.target.value)} /></label><button type="button" disabled={confirmation !== `DELETE ORIGINALS ${cleanupMonth}`} onClick={() => void cleanup()}>确认清理</button><button type="button" onClick={() => setCleanupMonth(null)}>取消</button></section>}</main>;
}
