import { useEffect, useState } from 'react';
import { CATEGORIES, type Batch, type FormOptions } from '@auto-reimbursement/contracts';
import { api, apiUrl } from '../api';

export function PreviewPage({ batchId }: { batchId: string | null }): React.JSX.Element {
  const [batch, setBatch] = useState<Batch | null>(null); const [revision, setRevision] = useState(0); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { if (batchId === null) { setBatch(null); return; } void api.batch(batchId).then(setBatch, (reason: unknown) => setError(reason instanceof Error ? reason.message : '加载预览失败')); }, [batchId]);
  const errorText = (reason: unknown, fallback: string) => reason instanceof Error ? `${typeof (reason as Error & { code?: unknown }).code === 'string' ? `${(reason as Error & { code: string }).code}：` : ''}${reason.message}` : fallback;
  async function save(options: FormOptions, notes: Record<string, string | null>): Promise<void> { if (!batch) return; setBusy(true); try { setBatch(await api.saveBatchOptions(batch.id, options, notes)); setRevision((value) => value + 1); } catch (reason) { setError(errorText(reason, '保存失败')); } finally { setBusy(false); } }
  async function move(category: typeof CATEGORIES[number], direction: -1 | 1): Promise<void> { if (!batch) return; setBusy(true); try { setBatch(await api.moveGroup(batch.id, category, direction)); setRevision((value) => value + 1); } catch (reason) { setError(errorText(reason, '调整失败')); } finally { setBusy(false); } }
  async function exportCurrent(): Promise<void> { if (!batch) return; setBusy(true); try { setBatch(await api.exportBatch(batch.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : '生成失败'); } finally { setBusy(false); } }
  if (batchId === null) return <main className="page-content"><h2>生成预览</h2><p>请先在报销池生成报销单，或从历史报销单中选择一个批次。</p></main>;
  if (batch === null) return <main className="page-content"><h2>生成预览</h2>{error ? <p role="alert">{error}</p> : <p>正在加载预览…</p>}</main>;
  const readonly = batch.pdfPath !== null;
  const notes = Object.fromEntries(batch.sheets.map((sheet) => [sheet.id, sheet.noteId]));
  const previewUrl = apiUrl(`/api/batches/${encodeURIComponent(batch.id)}/preview.pdf`);
  const pdfUrl = apiUrl(`/api/batches/${encodeURIComponent(batch.id)}/pdf`);
  return <main className="page-content"><h2>生成预览</h2>{error && <p role="alert">{error}</p>}<iframe title="完整报销 PDF 预览" className="pdf-preview" src={`${previewUrl}?revision=${revision}`} /><p><a href={batch.pdfPath === null ? previewUrl : pdfUrl} target="_blank" rel="noreferrer">打开或下载 PDF</a></p><fieldset disabled={readonly || busy}><legend>报销单选项</legend><label>部门<input value={batch.options.department} onChange={(e) => setBatch({ ...batch, options: { ...batch.options, department: e.target.value } })} /></label><label>日期<input value={batch.options.date ?? ''} onChange={(e) => setBatch({ ...batch, options: { ...batch.options, date: e.target.value || null } })} /></label><label>签名人<input value={batch.options.signerName} onChange={(e) => setBatch({ ...batch, options: { ...batch.options, signerName: e.target.value } })} /></label>{batch.sheets.map((sheet) => <label key={sheet.id}>第 {sheet.id} 页备注<select value={sheet.noteId ?? ''} onChange={(e) => { const value = e.target.value || null; setBatch({ ...batch, sheets: batch.sheets.map((item) => item.id === sheet.id ? { ...item, noteId: value } : item) }); }}><option value="">无备注</option>{batch.notes.map((note) => <option key={note.id} value={note.id}>{note.name}</option>)}</select></label>)}<button type="button" onClick={() => void save(batch.options, Object.fromEntries(batch.sheets.map((sheet) => [sheet.id, sheet.noteId])))}>保存预览设置</button></fieldset><section><h3>分类顺序</h3>{CATEGORIES.filter((category) => batch.sheets.some((sheet) => sheet.groups.some((group) => group.category === category))).map((category) => <p key={category}>{category} <button type="button" disabled={readonly || busy} onClick={() => void move(category, -1)}>上一页</button> <button type="button" disabled={readonly || busy} onClick={() => void move(category, 1)}>下一页</button></p>)}</section><button type="button" disabled={busy || readonly} onClick={() => void exportCurrent()}>生成 PDF</button>{readonly && <p>已导出的报销单不可修改。</p>}</main>;
}
