import { useEffect, useState } from 'react';
import type { Note, Rule, Settings } from '@auto-reimbursement/contracts';
import { api } from '../api';
import { NotesEditor } from '../components/NotesEditor';
import { RulesEditor } from '../components/RulesEditor';

export function SettingsPage(): React.JSX.Element {
  const [settings, setSettings] = useState<Settings | null>(null); const [notes, setNotes] = useState<Note[]>([]); const [rules, setRules] = useState<Rule[]>([]); const [configured, setConfigured] = useState<boolean | null>(null); const [download, setDownload] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void Promise.all([api.settings(), api.notes(), api.rules(), api.apiStatus()]).then(([next, nextNotes, nextRules, status]) => { setSettings(next); setNotes(nextNotes); setRules(nextRules); setConfigured(status.configured); }, (reason: unknown) => setError(reason instanceof Error ? reason.message : '加载设置失败')); }, []);
  async function createBackup(): Promise<void> { try { setError(null); setDownload((await api.backup()).downloadUrl); } catch (reason) { setError(reason instanceof Error ? reason.message : '备份失败'); } }
  if (settings === null) return <main className="page-content"><p>正在加载设置…</p>{error && <p role="alert">{error}</p>}</main>;
  return <main className="page-content"><h2>设置</h2>{error && <p role="alert">{error}</p>}<p>AI 服务：{configured === null ? '加载中' : configured ? '已配置' : '未配置'}</p><label>部门<input value={settings.department} onChange={(e) => setSettings({ ...settings, department: e.target.value })} /></label><label>日期默认值<select value={settings.dateMode} onChange={(e) => setSettings({ ...settings, dateMode: e.target.value as Settings['dateMode'] })}><option value="today">当天</option><option value="blank">留空</option><option value="custom">自定义</option></select></label><label>自定义日期<input value={settings.customDate ?? ''} onChange={(e) => setSettings({ ...settings, customDate: e.target.value || null })} /></label><label>金额阈值<input type="number" min="0.8" max="1" step="0.01" value={settings.amountThreshold} onChange={(e) => setSettings({ ...settings, amountThreshold: Number(e.target.value) })} /></label><label>分类阈值<input type="number" min="0.7" max="1" step="0.01" value={settings.categoryThreshold} onChange={(e) => setSettings({ ...settings, categoryThreshold: Number(e.target.value) })} /></label><label>签名方式<select value={settings.signerMode} onChange={(e) => setSettings({ ...settings, signerMode: e.target.value as Settings['signerMode'] })}><option value="text">文字</option><option value="image">图片</option></select></label><label>签名人<input value={settings.signerName} onChange={(e) => setSettings({ ...settings, signerName: e.target.value })} /></label><label>上传签名<input type="file" accept="image/*" onChange={(e) => { const file = e.target.files?.[0]; if (file) void api.saveSignature(file).then(setSettings, (reason: unknown) => setError(reason instanceof Error ? reason.message : '上传失败')); }} /></label><button type="button" onClick={() => void api.saveSettings(settings).then(setSettings, (reason: unknown) => setError(reason instanceof Error ? reason.message : '保存失败'))}>保存设置</button><NotesEditor notes={notes} onSave={async (note) => { const saved = await api.saveNote(note); setNotes((current) => [...current.filter((item) => item.id !== note.id), saved]); }} onDelete={async (id) => { await api.deleteNote(id); setNotes((current) => current.filter((note) => note.id !== id)); }} /><RulesEditor rules={rules} onSave={async (rule) => { const saved = await api.saveRule(rule); setRules((current) => [...current.filter((item) => item.id !== rule.id), saved]); }} onDelete={async (id) => { await api.deleteRule(id); setRules((current) => current.filter((rule) => rule.id !== id)); }} /><section><h3>本地备份</h3><p>此备份包含数据库、设置、学习规则和文件索引，不包含图片和 PDF</p><p>如需完整恢复媒体文件，请复制整个数据文件夹。</p><button type="button" onClick={() => void createBackup()}>备份全部数据</button>{download && <p><a href={download}>下载备份</a></p>}</section></main>;
}
